# fly.toml app configuration file generated for gymcatch on 2025-03-01T20:33:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gymcatch'
primary_region = 'mad'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
